version: '3.8'
services:

  service-db:
    image: postgres:14.3
    environment:
      POSTGRES_USER: jdbc
      POSTGRES_PASSWORD: jdbc
    ports:
      - "5433:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_jdbc
    image: dpage/pgadmin4:8.6
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"